version: '3'

volumes:
  unity-accelerator.v1_v2-volume:
    driver: 'local'

services:
  unity-accelerator:
    build:
      context: .
      dockerfile: Dockerfile.v1_v2
    image: unity-accelerator:v1_v2
    volumes:
      - unity-accelerator.v1_v2-volume:/root/.config/unity-accelerator
    ports:
      - "10080:10080"
      - "8080:80"
      - "8126:8126"
